import os

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 800
FPS = 60

# Paths
TILES_PATH = os.path.join('data', 'tiles')
RESOURCES_PATH = os.path.join('data', 'resources')

# Map parameters
TILE_WIDTH = 60
TILE_HEIGHT = 60
TILES_NUM_WITDH = 64
TILES_NUM_HEIGHT = 64
MAP_WIDTH = TILE_WIDTH * TILES_NUM_WITDH
MAP_HEIGHT = TILE_HEIGHT * TILES_NUM_HEIGHT
